language: python
python:
  - 3.5
  - 3.6
os:
  - linux
  - osx
install:
  - pip install -U pip
  - pip install -U wheel setuptools
  - pip install -r requirements-dev.txt
script:
  - python -m pytest
